import type { WorkoutRoutine } from "./types"

export const defaultRoutines: WorkoutRoutine[] = [
  {
    id: "fullbody-beginner",
    name: "Entrenamiento Full Body para Principiantes",
    description: "Una rutina completa para todo el cuerpo ideal para principiantes",
    exercises: [
      {
        id: "squat-beginner",
        name: "Sentadillas",
        sets: 3,
        reps: 10,
        weight: 0,
        categoryId: "legs",
        restTime: 60,
      },
      {
        id: "pushup-beginner",
        name: "Flexiones",
        sets: 3,
        reps: 8,
        weight: 0,
        categoryId: "chest",
        restTime: 60,
      },
      {
        id: "row-beginner",
        name: "Remo con mancuernas",
        sets: 3,
        reps: 10,
        weight: 5,
        categoryId: "back",
        restTime: 60,
      },
      {
        id: "plank-beginner",
        name: "Plancha",
        sets: 3,
        reps: 1,
        weight: 0,
        notes: "Mantener 30 segundos",
        categoryId: "abs",
        restTime: 60,
      },
    ],
    frequency: ["lunes", "miércoles", "viernes"],
    duration: 45,
    level: "beginner",
    category: "strength",
  },
  {
    id: "upper-intermediate",
    name: "Entrenamiento de Tren Superior",
    description: "Rutina enfocada en desarrollar la parte superior del cuerpo",
    exercises: [
      {
        id: "bench-press",
        name: "Press de banca",
        sets: 4,
        reps: 8,
        weight: 60,
        categoryId: "chest",
        restTime: 90,
      },
      {
        id: "pullups",
        name: "Dominadas",
        sets: 4,
        reps: 8,
        weight: 0,
        categoryId: "back",
        restTime: 90,
      },
      {
        id: "shoulder-press",
        name: "Press de hombros",
        sets: 3,
        reps: 10,
        weight: 40,
        categoryId: "shoulders",
        restTime: 90,
      },
      {
        id: "bicep-curl",
        name: "Curl de bíceps",
        sets: 3,
        reps: 12,
        weight: 15,
        categoryId: "arms",
        restTime: 60,
      },
      {
        id: "tricep-extension",
        name: "Extensiones de tríceps",
        sets: 3,
        reps: 12,
        weight: 15,
        categoryId: "arms",
        restTime: 60,
      },
    ],
    frequency: ["lunes", "jueves"],
    duration: 60,
    level: "intermediate",
    category: "strength",
  },
  {
    id: "lower-intermediate",
    name: "Entrenamiento de Tren Inferior",
    description: "Rutina enfocada en desarrollar la parte inferior del cuerpo",
    exercises: [
      {
        id: "squat",
        name: "Sentadillas con barra",
        sets: 4,
        reps: 8,
        weight: 80,
        categoryId: "legs",
        restTime: 120,
      },
      {
        id: "deadlift",
        name: "Peso muerto",
        sets: 4,
        reps: 6,
        weight: 100,
        categoryId: "legs",
        restTime: 120,
      },
      {
        id: "lunges",
        name: "Zancadas",
        sets: 3,
        reps: 10,
        weight: 20,
        categoryId: "legs",
        restTime: 90,
      },
      {
        id: "calf-raises",
        name: "Elevaciones de gemelos",
        sets: 3,
        reps: 15,
        weight: 30,
        categoryId: "legs",
        restTime: 60,
      },
    ],
    frequency: ["martes", "viernes"],
    duration: 60,
    level: "intermediate",
    category: "strength",
  },
  {
    id: "hiit-cardio",
    name: "HIIT Cardio",
    description: "Entrenamiento de alta intensidad para quemar calorías",
    exercises: [
      {
        id: "burpees",
        name: "Burpees",
        sets: 4,
        reps: 15,
        weight: 0,
        categoryId: "cardio",
        restTime: 30,
      },
      {
        id: "mountain-climbers",
        name: "Mountain Climbers",
        sets: 4,
        reps: 30,
        weight: 0,
        categoryId: "cardio",
        restTime: 30,
      },
      {
        id: "jumping-jacks",
        name: "Jumping Jacks",
        sets: 4,
        reps: 30,
        weight: 0,
        categoryId: "cardio",
        restTime: 30,
      },
      {
        id: "high-knees",
        name: "High Knees",
        sets: 4,
        reps: 30,
        weight: 0,
        categoryId: "cardio",
        restTime: 30,
      },
    ],
    frequency: ["miércoles", "sábado"],
    duration: 30,
    level: "intermediate",
    category: "cardio",
  },
]

export const exercisesByCategory = {
  chest: [
    "Press de banca",
    "Press inclinado",
    "Press declinado",
    "Aperturas con mancuernas",
    "Flexiones",
    "Fondos en paralelas",
    "Pullover",
    "Crossover en polea",
  ],
  back: [
    "Dominadas",
    "Remo con barra",
    "Remo con mancuerna",
    "Jalón al pecho",
    "Peso muerto",
    "Pull-over",
    "Hiperextensiones",
    "Remo en máquina",
  ],
  legs: [
    "Sentadillas",
    "Peso muerto",
    "Prensa de piernas",
    "Extensiones de cuádriceps",
    "Curl femoral",
    "Zancadas",
    "Elevaciones de gemelos",
    "Aductores",
  ],
  shoulders: [
    "Press militar",
    "Elevaciones laterales",
    "Elevaciones frontales",
    "Pájaro",
    "Face pull",
    "Press Arnold",
    "Encogimientos de hombros",
    "Remo al mentón",
  ],
  arms: [
    "Curl de bíceps",
    "Curl martillo",
    "Curl predicador",
    "Curl concentrado",
    "Extensiones de tríceps",
    "Press francés",
    "Fondos",
    "Patada de tríceps",
  ],
  abs: [
    "Crunch",
    "Plancha",
    "Russian twist",
    "Elevaciones de piernas",
    "Mountain climber",
    "Rueda abdominal",
    "Hollow hold",
    "Dragon flag",
  ],
  cardio: [
    "Correr",
    "Bicicleta",
    "Elíptica",
    "Saltar la cuerda",
    "Burpees",
    "Jumping jacks",
    "Mountain climbers",
    "High knees",
  ],
}

